//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Settings/InputActionMaps/GameplayInputMaps.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace GameLogic
{
    public partial class @GameplayInputMaps: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameplayInputMaps()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameplayInputMaps"",
    ""maps"": [
        {
            ""name"": ""Common"",
            ""id"": ""62cc3f4f-b60f-42ea-b09e-54fa016cb4a9"",
            ""actions"": [
                {
                    ""name"": ""MouseLeftClick"",
                    ""type"": ""Button"",
                    ""id"": ""ee942446-953e-4e01-858a-14fb84e7cfce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MouseRightClick"",
                    ""type"": ""Button"",
                    ""id"": ""43901800-30f2-45f0-8c87-537ced39217d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""Value"",
                    ""id"": ""ae748020-764b-49e2-8b2c-07aac79e7195"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Escape"",
                    ""type"": ""Button"",
                    ""id"": ""2a29ecf0-dd60-403e-9b4a-46f0aa0cf713"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AltHotKey"",
                    ""type"": ""Button"",
                    ""id"": ""18ceb679-e8b6-49d1-8e9e-f06f6f4c3d67"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CtrlHotKey"",
                    ""type"": ""Button"",
                    ""id"": ""fb66b8d5-69c1-4920-9a25-ee66e5e6eaf3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1396f0e3-a498-4631-9c33-277fc62e92ab"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseLeftClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2c9ad183-9b3e-4507-b3fe-0246105f506f"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MouseRightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0808e1a1-969a-4332-95a0-afbb9cc3ca32"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d1c4ff6a-f08a-48fb-b18f-e23797c5df44"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Escape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fbd33764-6196-4086-8ea7-20caa65c1b99"",
                    ""path"": ""<Keyboard>/leftAlt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AltHotKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7bb968a-1d8a-4640-b252-03ae48bc3b79"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CtrlHotKey"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Topdown"",
            ""id"": ""6a4f8c0c-c4a5-4ccb-b55c-974440380f92"",
            ""actions"": [
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""2d656791-0710-4896-a366-d54ac1e26ba5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DragActivation"",
                    ""type"": ""Button"",
                    ""id"": ""d9cfff9e-a4f6-4da4-a696-ecda8e9262a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DragPerform"",
                    ""type"": ""Value"",
                    ""id"": ""6a5af712-34c7-4952-a0bf-a67bb843a6fe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Confirm"",
                    ""type"": ""Button"",
                    ""id"": ""34275364-de5d-4a2d-a92c-db193d5805c9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Focus"",
                    ""type"": ""Button"",
                    ""id"": ""3c7b13cd-7639-4028-9489-08764149736c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reposition"",
                    ""type"": ""Button"",
                    ""id"": ""417ea0ff-b7de-4f4f-8aa0-55c0e54cfa0e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1323e2af-40c4-4e5e-ae52-810306d335c6"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=0.00083)"",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bb1ff79c-c6da-4e7f-ac4e-a84a99f8309d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Hold"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DragActivation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""27d519a8-d2b7-4591-8cd0-8c94e343013b"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Confirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ad85b1d6-a795-47a1-b17c-e0eaa5ffb4b1"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2(x=0.1,y=0.1)"",
                    ""groups"": """",
                    ""action"": ""DragPerform"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28fb798d-5554-4edc-9912-004455cd82e1"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Focus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f084eaba-c46d-4817-b899-e9a649b31d91"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reposition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Constructing"",
            ""id"": ""856632e0-8aff-4825-b29c-f2c1d9d68322"",
            ""actions"": [
                {
                    ""name"": ""SwitchConstructStatus"",
                    ""type"": ""Button"",
                    ""id"": ""52241623-45a0-489a-b74c-a55f45464dce"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConstructOrbit"",
                    ""type"": ""Button"",
                    ""id"": ""634ee585-b295-407d-9cff-b8a1e930960f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConstructPlanet"",
                    ""type"": ""Button"",
                    ""id"": ""f1941711-dae8-4693-9bf5-8eb418161000"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""00a1916b-3df4-4a8b-9902-89f8d9411a96"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConstructOrbit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3cf57a5a-7e52-41f9-97df-e6940ece7170"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConstructPlanet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b43487a0-130e-49f7-bed4-9c11eb3c77a0"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchConstructStatus"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""AbilityCast"",
            ""id"": ""f1d3c777-1920-4793-9896-e98f48a83fd7"",
            ""actions"": [
                {
                    ""name"": ""AbilityCast_Q"",
                    ""type"": ""Button"",
                    ""id"": ""76cd1dd6-db4a-4159-b3f5-49690a4070d7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityCast_W"",
                    ""type"": ""Button"",
                    ""id"": ""ed25b787-1aba-4dcd-9b0d-88cd460bb033"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityCast_E"",
                    ""type"": ""Button"",
                    ""id"": ""3ed0e960-2b96-41fc-a6f7-cd7333616156"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityCast_R"",
                    ""type"": ""Button"",
                    ""id"": ""86b5f365-d3f6-46da-a1c3-43226f60455d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityCast_T"",
                    ""type"": ""Button"",
                    ""id"": ""1f98fc8e-eb08-4bf9-bd33-8349d51044ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AbilityCast_Y"",
                    ""type"": ""Button"",
                    ""id"": ""4aff903b-7723-4501-89ea-38e18114f2d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectorPosition"",
                    ""type"": ""Value"",
                    ""id"": ""d1a67ded-a474-47a5-bb7b-46c73f7b7280"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SelectorConfirm"",
                    ""type"": ""Button"",
                    ""id"": ""fa1eec31-a7a1-4848-8f21-9a929a1f0b53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectorCancel"",
                    ""type"": ""Button"",
                    ""id"": ""6b068622-98ef-4f9c-bab4-72a25254dfd0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""7dbcbb6b-50c2-486a-aeba-eb499fdb0384"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityCast_Q"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5759ed5d-5b91-4ed1-be04-60d42e50e3ca"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityCast_W"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa2262ab-b534-4120-9632-b5d5bdad2db8"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityCast_R"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3db3f64e-7869-46a3-821b-637e5c6da61a"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bf63c27-6ecc-4694-8452-5d9d24a3f919"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectorConfirm"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a602fcb1-cfa2-43db-856d-e12ff67f02fb"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press(behavior=1)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectorCancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7bf3af5-1d9d-466e-95c8-44aaae24e3e9"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityCast_E"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""165bcc38-118d-48da-9569-ef6cc6dc7d05"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityCast_T"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""823a715c-424f-4804-a0d5-449121b898da"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AbilityCast_Y"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""SpeedControl"",
            ""id"": ""039284dc-f063-4a34-8fef-03247920d0ab"",
            ""actions"": [
                {
                    ""name"": ""SpeedControl_0"",
                    ""type"": ""Button"",
                    ""id"": ""4b183e83-6704-4b7e-991e-402ffc6494dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpeedControl_1"",
                    ""type"": ""Button"",
                    ""id"": ""5e5035d0-d62b-4d7d-b658-5cf9a290999b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpeedControl_2"",
                    ""type"": ""Button"",
                    ""id"": ""7a3ae481-d68c-40b8-9539-16345be53e3c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpeedControl_3"",
                    ""type"": ""Button"",
                    ""id"": ""6e3c0584-ea3c-4b79-9b63-980c4c769055"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""340439bf-6c7f-4b13-9949-58abb1fb1f27"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeedControl_0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24a2eda1-80ff-408f-8f73-57301abaa580"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeedControl_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7aec0f74-b3eb-4ccb-aeba-c663a66ddc18"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeedControl_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9c0f493e-7cc0-4bb4-a4de-fb9398453c95"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeedControl_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Common
            m_Common = asset.FindActionMap("Common", throwIfNotFound: true);
            m_Common_MouseLeftClick = m_Common.FindAction("MouseLeftClick", throwIfNotFound: true);
            m_Common_MouseRightClick = m_Common.FindAction("MouseRightClick", throwIfNotFound: true);
            m_Common_MousePosition = m_Common.FindAction("MousePosition", throwIfNotFound: true);
            m_Common_Escape = m_Common.FindAction("Escape", throwIfNotFound: true);
            m_Common_AltHotKey = m_Common.FindAction("AltHotKey", throwIfNotFound: true);
            m_Common_CtrlHotKey = m_Common.FindAction("CtrlHotKey", throwIfNotFound: true);
            // Topdown
            m_Topdown = asset.FindActionMap("Topdown", throwIfNotFound: true);
            m_Topdown_Zoom = m_Topdown.FindAction("Zoom", throwIfNotFound: true);
            m_Topdown_DragActivation = m_Topdown.FindAction("DragActivation", throwIfNotFound: true);
            m_Topdown_DragPerform = m_Topdown.FindAction("DragPerform", throwIfNotFound: true);
            m_Topdown_Confirm = m_Topdown.FindAction("Confirm", throwIfNotFound: true);
            m_Topdown_Focus = m_Topdown.FindAction("Focus", throwIfNotFound: true);
            m_Topdown_Reposition = m_Topdown.FindAction("Reposition", throwIfNotFound: true);
            // Constructing
            m_Constructing = asset.FindActionMap("Constructing", throwIfNotFound: true);
            m_Constructing_SwitchConstructStatus = m_Constructing.FindAction("SwitchConstructStatus", throwIfNotFound: true);
            m_Constructing_ConstructOrbit = m_Constructing.FindAction("ConstructOrbit", throwIfNotFound: true);
            m_Constructing_ConstructPlanet = m_Constructing.FindAction("ConstructPlanet", throwIfNotFound: true);
            // AbilityCast
            m_AbilityCast = asset.FindActionMap("AbilityCast", throwIfNotFound: true);
            m_AbilityCast_AbilityCast_Q = m_AbilityCast.FindAction("AbilityCast_Q", throwIfNotFound: true);
            m_AbilityCast_AbilityCast_W = m_AbilityCast.FindAction("AbilityCast_W", throwIfNotFound: true);
            m_AbilityCast_AbilityCast_E = m_AbilityCast.FindAction("AbilityCast_E", throwIfNotFound: true);
            m_AbilityCast_AbilityCast_R = m_AbilityCast.FindAction("AbilityCast_R", throwIfNotFound: true);
            m_AbilityCast_AbilityCast_T = m_AbilityCast.FindAction("AbilityCast_T", throwIfNotFound: true);
            m_AbilityCast_AbilityCast_Y = m_AbilityCast.FindAction("AbilityCast_Y", throwIfNotFound: true);
            m_AbilityCast_SelectorPosition = m_AbilityCast.FindAction("SelectorPosition", throwIfNotFound: true);
            m_AbilityCast_SelectorConfirm = m_AbilityCast.FindAction("SelectorConfirm", throwIfNotFound: true);
            m_AbilityCast_SelectorCancel = m_AbilityCast.FindAction("SelectorCancel", throwIfNotFound: true);
            // SpeedControl
            m_SpeedControl = asset.FindActionMap("SpeedControl", throwIfNotFound: true);
            m_SpeedControl_SpeedControl_0 = m_SpeedControl.FindAction("SpeedControl_0", throwIfNotFound: true);
            m_SpeedControl_SpeedControl_1 = m_SpeedControl.FindAction("SpeedControl_1", throwIfNotFound: true);
            m_SpeedControl_SpeedControl_2 = m_SpeedControl.FindAction("SpeedControl_2", throwIfNotFound: true);
            m_SpeedControl_SpeedControl_3 = m_SpeedControl.FindAction("SpeedControl_3", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Common
        private readonly InputActionMap m_Common;
        private List<ICommonActions> m_CommonActionsCallbackInterfaces = new List<ICommonActions>();
        private readonly InputAction m_Common_MouseLeftClick;
        private readonly InputAction m_Common_MouseRightClick;
        private readonly InputAction m_Common_MousePosition;
        private readonly InputAction m_Common_Escape;
        private readonly InputAction m_Common_AltHotKey;
        private readonly InputAction m_Common_CtrlHotKey;
        public struct CommonActions
        {
            private @GameplayInputMaps m_Wrapper;
            public CommonActions(@GameplayInputMaps wrapper) { m_Wrapper = wrapper; }
            public InputAction @MouseLeftClick => m_Wrapper.m_Common_MouseLeftClick;
            public InputAction @MouseRightClick => m_Wrapper.m_Common_MouseRightClick;
            public InputAction @MousePosition => m_Wrapper.m_Common_MousePosition;
            public InputAction @Escape => m_Wrapper.m_Common_Escape;
            public InputAction @AltHotKey => m_Wrapper.m_Common_AltHotKey;
            public InputAction @CtrlHotKey => m_Wrapper.m_Common_CtrlHotKey;
            public InputActionMap Get() { return m_Wrapper.m_Common; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(CommonActions set) { return set.Get(); }
            public void AddCallbacks(ICommonActions instance)
            {
                if (instance == null || m_Wrapper.m_CommonActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_CommonActionsCallbackInterfaces.Add(instance);
                @MouseLeftClick.started += instance.OnMouseLeftClick;
                @MouseLeftClick.performed += instance.OnMouseLeftClick;
                @MouseLeftClick.canceled += instance.OnMouseLeftClick;
                @MouseRightClick.started += instance.OnMouseRightClick;
                @MouseRightClick.performed += instance.OnMouseRightClick;
                @MouseRightClick.canceled += instance.OnMouseRightClick;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @Escape.started += instance.OnEscape;
                @Escape.performed += instance.OnEscape;
                @Escape.canceled += instance.OnEscape;
                @AltHotKey.started += instance.OnAltHotKey;
                @AltHotKey.performed += instance.OnAltHotKey;
                @AltHotKey.canceled += instance.OnAltHotKey;
                @CtrlHotKey.started += instance.OnCtrlHotKey;
                @CtrlHotKey.performed += instance.OnCtrlHotKey;
                @CtrlHotKey.canceled += instance.OnCtrlHotKey;
            }

            private void UnregisterCallbacks(ICommonActions instance)
            {
                @MouseLeftClick.started -= instance.OnMouseLeftClick;
                @MouseLeftClick.performed -= instance.OnMouseLeftClick;
                @MouseLeftClick.canceled -= instance.OnMouseLeftClick;
                @MouseRightClick.started -= instance.OnMouseRightClick;
                @MouseRightClick.performed -= instance.OnMouseRightClick;
                @MouseRightClick.canceled -= instance.OnMouseRightClick;
                @MousePosition.started -= instance.OnMousePosition;
                @MousePosition.performed -= instance.OnMousePosition;
                @MousePosition.canceled -= instance.OnMousePosition;
                @Escape.started -= instance.OnEscape;
                @Escape.performed -= instance.OnEscape;
                @Escape.canceled -= instance.OnEscape;
                @AltHotKey.started -= instance.OnAltHotKey;
                @AltHotKey.performed -= instance.OnAltHotKey;
                @AltHotKey.canceled -= instance.OnAltHotKey;
                @CtrlHotKey.started -= instance.OnCtrlHotKey;
                @CtrlHotKey.performed -= instance.OnCtrlHotKey;
                @CtrlHotKey.canceled -= instance.OnCtrlHotKey;
            }

            public void RemoveCallbacks(ICommonActions instance)
            {
                if (m_Wrapper.m_CommonActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ICommonActions instance)
            {
                foreach (var item in m_Wrapper.m_CommonActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_CommonActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public CommonActions @Common => new CommonActions(this);

        // Topdown
        private readonly InputActionMap m_Topdown;
        private List<ITopdownActions> m_TopdownActionsCallbackInterfaces = new List<ITopdownActions>();
        private readonly InputAction m_Topdown_Zoom;
        private readonly InputAction m_Topdown_DragActivation;
        private readonly InputAction m_Topdown_DragPerform;
        private readonly InputAction m_Topdown_Confirm;
        private readonly InputAction m_Topdown_Focus;
        private readonly InputAction m_Topdown_Reposition;
        public struct TopdownActions
        {
            private @GameplayInputMaps m_Wrapper;
            public TopdownActions(@GameplayInputMaps wrapper) { m_Wrapper = wrapper; }
            public InputAction @Zoom => m_Wrapper.m_Topdown_Zoom;
            public InputAction @DragActivation => m_Wrapper.m_Topdown_DragActivation;
            public InputAction @DragPerform => m_Wrapper.m_Topdown_DragPerform;
            public InputAction @Confirm => m_Wrapper.m_Topdown_Confirm;
            public InputAction @Focus => m_Wrapper.m_Topdown_Focus;
            public InputAction @Reposition => m_Wrapper.m_Topdown_Reposition;
            public InputActionMap Get() { return m_Wrapper.m_Topdown; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(TopdownActions set) { return set.Get(); }
            public void AddCallbacks(ITopdownActions instance)
            {
                if (instance == null || m_Wrapper.m_TopdownActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_TopdownActionsCallbackInterfaces.Add(instance);
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @DragActivation.started += instance.OnDragActivation;
                @DragActivation.performed += instance.OnDragActivation;
                @DragActivation.canceled += instance.OnDragActivation;
                @DragPerform.started += instance.OnDragPerform;
                @DragPerform.performed += instance.OnDragPerform;
                @DragPerform.canceled += instance.OnDragPerform;
                @Confirm.started += instance.OnConfirm;
                @Confirm.performed += instance.OnConfirm;
                @Confirm.canceled += instance.OnConfirm;
                @Focus.started += instance.OnFocus;
                @Focus.performed += instance.OnFocus;
                @Focus.canceled += instance.OnFocus;
                @Reposition.started += instance.OnReposition;
                @Reposition.performed += instance.OnReposition;
                @Reposition.canceled += instance.OnReposition;
            }

            private void UnregisterCallbacks(ITopdownActions instance)
            {
                @Zoom.started -= instance.OnZoom;
                @Zoom.performed -= instance.OnZoom;
                @Zoom.canceled -= instance.OnZoom;
                @DragActivation.started -= instance.OnDragActivation;
                @DragActivation.performed -= instance.OnDragActivation;
                @DragActivation.canceled -= instance.OnDragActivation;
                @DragPerform.started -= instance.OnDragPerform;
                @DragPerform.performed -= instance.OnDragPerform;
                @DragPerform.canceled -= instance.OnDragPerform;
                @Confirm.started -= instance.OnConfirm;
                @Confirm.performed -= instance.OnConfirm;
                @Confirm.canceled -= instance.OnConfirm;
                @Focus.started -= instance.OnFocus;
                @Focus.performed -= instance.OnFocus;
                @Focus.canceled -= instance.OnFocus;
                @Reposition.started -= instance.OnReposition;
                @Reposition.performed -= instance.OnReposition;
                @Reposition.canceled -= instance.OnReposition;
            }

            public void RemoveCallbacks(ITopdownActions instance)
            {
                if (m_Wrapper.m_TopdownActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ITopdownActions instance)
            {
                foreach (var item in m_Wrapper.m_TopdownActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_TopdownActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public TopdownActions @Topdown => new TopdownActions(this);

        // Constructing
        private readonly InputActionMap m_Constructing;
        private List<IConstructingActions> m_ConstructingActionsCallbackInterfaces = new List<IConstructingActions>();
        private readonly InputAction m_Constructing_SwitchConstructStatus;
        private readonly InputAction m_Constructing_ConstructOrbit;
        private readonly InputAction m_Constructing_ConstructPlanet;
        public struct ConstructingActions
        {
            private @GameplayInputMaps m_Wrapper;
            public ConstructingActions(@GameplayInputMaps wrapper) { m_Wrapper = wrapper; }
            public InputAction @SwitchConstructStatus => m_Wrapper.m_Constructing_SwitchConstructStatus;
            public InputAction @ConstructOrbit => m_Wrapper.m_Constructing_ConstructOrbit;
            public InputAction @ConstructPlanet => m_Wrapper.m_Constructing_ConstructPlanet;
            public InputActionMap Get() { return m_Wrapper.m_Constructing; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(ConstructingActions set) { return set.Get(); }
            public void AddCallbacks(IConstructingActions instance)
            {
                if (instance == null || m_Wrapper.m_ConstructingActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_ConstructingActionsCallbackInterfaces.Add(instance);
                @SwitchConstructStatus.started += instance.OnSwitchConstructStatus;
                @SwitchConstructStatus.performed += instance.OnSwitchConstructStatus;
                @SwitchConstructStatus.canceled += instance.OnSwitchConstructStatus;
                @ConstructOrbit.started += instance.OnConstructOrbit;
                @ConstructOrbit.performed += instance.OnConstructOrbit;
                @ConstructOrbit.canceled += instance.OnConstructOrbit;
                @ConstructPlanet.started += instance.OnConstructPlanet;
                @ConstructPlanet.performed += instance.OnConstructPlanet;
                @ConstructPlanet.canceled += instance.OnConstructPlanet;
            }

            private void UnregisterCallbacks(IConstructingActions instance)
            {
                @SwitchConstructStatus.started -= instance.OnSwitchConstructStatus;
                @SwitchConstructStatus.performed -= instance.OnSwitchConstructStatus;
                @SwitchConstructStatus.canceled -= instance.OnSwitchConstructStatus;
                @ConstructOrbit.started -= instance.OnConstructOrbit;
                @ConstructOrbit.performed -= instance.OnConstructOrbit;
                @ConstructOrbit.canceled -= instance.OnConstructOrbit;
                @ConstructPlanet.started -= instance.OnConstructPlanet;
                @ConstructPlanet.performed -= instance.OnConstructPlanet;
                @ConstructPlanet.canceled -= instance.OnConstructPlanet;
            }

            public void RemoveCallbacks(IConstructingActions instance)
            {
                if (m_Wrapper.m_ConstructingActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IConstructingActions instance)
            {
                foreach (var item in m_Wrapper.m_ConstructingActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_ConstructingActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public ConstructingActions @Constructing => new ConstructingActions(this);

        // AbilityCast
        private readonly InputActionMap m_AbilityCast;
        private List<IAbilityCastActions> m_AbilityCastActionsCallbackInterfaces = new List<IAbilityCastActions>();
        private readonly InputAction m_AbilityCast_AbilityCast_Q;
        private readonly InputAction m_AbilityCast_AbilityCast_W;
        private readonly InputAction m_AbilityCast_AbilityCast_E;
        private readonly InputAction m_AbilityCast_AbilityCast_R;
        private readonly InputAction m_AbilityCast_AbilityCast_T;
        private readonly InputAction m_AbilityCast_AbilityCast_Y;
        private readonly InputAction m_AbilityCast_SelectorPosition;
        private readonly InputAction m_AbilityCast_SelectorConfirm;
        private readonly InputAction m_AbilityCast_SelectorCancel;
        public struct AbilityCastActions
        {
            private @GameplayInputMaps m_Wrapper;
            public AbilityCastActions(@GameplayInputMaps wrapper) { m_Wrapper = wrapper; }
            public InputAction @AbilityCast_Q => m_Wrapper.m_AbilityCast_AbilityCast_Q;
            public InputAction @AbilityCast_W => m_Wrapper.m_AbilityCast_AbilityCast_W;
            public InputAction @AbilityCast_E => m_Wrapper.m_AbilityCast_AbilityCast_E;
            public InputAction @AbilityCast_R => m_Wrapper.m_AbilityCast_AbilityCast_R;
            public InputAction @AbilityCast_T => m_Wrapper.m_AbilityCast_AbilityCast_T;
            public InputAction @AbilityCast_Y => m_Wrapper.m_AbilityCast_AbilityCast_Y;
            public InputAction @SelectorPosition => m_Wrapper.m_AbilityCast_SelectorPosition;
            public InputAction @SelectorConfirm => m_Wrapper.m_AbilityCast_SelectorConfirm;
            public InputAction @SelectorCancel => m_Wrapper.m_AbilityCast_SelectorCancel;
            public InputActionMap Get() { return m_Wrapper.m_AbilityCast; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(AbilityCastActions set) { return set.Get(); }
            public void AddCallbacks(IAbilityCastActions instance)
            {
                if (instance == null || m_Wrapper.m_AbilityCastActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_AbilityCastActionsCallbackInterfaces.Add(instance);
                @AbilityCast_Q.started += instance.OnAbilityCast_Q;
                @AbilityCast_Q.performed += instance.OnAbilityCast_Q;
                @AbilityCast_Q.canceled += instance.OnAbilityCast_Q;
                @AbilityCast_W.started += instance.OnAbilityCast_W;
                @AbilityCast_W.performed += instance.OnAbilityCast_W;
                @AbilityCast_W.canceled += instance.OnAbilityCast_W;
                @AbilityCast_E.started += instance.OnAbilityCast_E;
                @AbilityCast_E.performed += instance.OnAbilityCast_E;
                @AbilityCast_E.canceled += instance.OnAbilityCast_E;
                @AbilityCast_R.started += instance.OnAbilityCast_R;
                @AbilityCast_R.performed += instance.OnAbilityCast_R;
                @AbilityCast_R.canceled += instance.OnAbilityCast_R;
                @AbilityCast_T.started += instance.OnAbilityCast_T;
                @AbilityCast_T.performed += instance.OnAbilityCast_T;
                @AbilityCast_T.canceled += instance.OnAbilityCast_T;
                @AbilityCast_Y.started += instance.OnAbilityCast_Y;
                @AbilityCast_Y.performed += instance.OnAbilityCast_Y;
                @AbilityCast_Y.canceled += instance.OnAbilityCast_Y;
                @SelectorPosition.started += instance.OnSelectorPosition;
                @SelectorPosition.performed += instance.OnSelectorPosition;
                @SelectorPosition.canceled += instance.OnSelectorPosition;
                @SelectorConfirm.started += instance.OnSelectorConfirm;
                @SelectorConfirm.performed += instance.OnSelectorConfirm;
                @SelectorConfirm.canceled += instance.OnSelectorConfirm;
                @SelectorCancel.started += instance.OnSelectorCancel;
                @SelectorCancel.performed += instance.OnSelectorCancel;
                @SelectorCancel.canceled += instance.OnSelectorCancel;
            }

            private void UnregisterCallbacks(IAbilityCastActions instance)
            {
                @AbilityCast_Q.started -= instance.OnAbilityCast_Q;
                @AbilityCast_Q.performed -= instance.OnAbilityCast_Q;
                @AbilityCast_Q.canceled -= instance.OnAbilityCast_Q;
                @AbilityCast_W.started -= instance.OnAbilityCast_W;
                @AbilityCast_W.performed -= instance.OnAbilityCast_W;
                @AbilityCast_W.canceled -= instance.OnAbilityCast_W;
                @AbilityCast_E.started -= instance.OnAbilityCast_E;
                @AbilityCast_E.performed -= instance.OnAbilityCast_E;
                @AbilityCast_E.canceled -= instance.OnAbilityCast_E;
                @AbilityCast_R.started -= instance.OnAbilityCast_R;
                @AbilityCast_R.performed -= instance.OnAbilityCast_R;
                @AbilityCast_R.canceled -= instance.OnAbilityCast_R;
                @AbilityCast_T.started -= instance.OnAbilityCast_T;
                @AbilityCast_T.performed -= instance.OnAbilityCast_T;
                @AbilityCast_T.canceled -= instance.OnAbilityCast_T;
                @AbilityCast_Y.started -= instance.OnAbilityCast_Y;
                @AbilityCast_Y.performed -= instance.OnAbilityCast_Y;
                @AbilityCast_Y.canceled -= instance.OnAbilityCast_Y;
                @SelectorPosition.started -= instance.OnSelectorPosition;
                @SelectorPosition.performed -= instance.OnSelectorPosition;
                @SelectorPosition.canceled -= instance.OnSelectorPosition;
                @SelectorConfirm.started -= instance.OnSelectorConfirm;
                @SelectorConfirm.performed -= instance.OnSelectorConfirm;
                @SelectorConfirm.canceled -= instance.OnSelectorConfirm;
                @SelectorCancel.started -= instance.OnSelectorCancel;
                @SelectorCancel.performed -= instance.OnSelectorCancel;
                @SelectorCancel.canceled -= instance.OnSelectorCancel;
            }

            public void RemoveCallbacks(IAbilityCastActions instance)
            {
                if (m_Wrapper.m_AbilityCastActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IAbilityCastActions instance)
            {
                foreach (var item in m_Wrapper.m_AbilityCastActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_AbilityCastActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public AbilityCastActions @AbilityCast => new AbilityCastActions(this);

        // SpeedControl
        private readonly InputActionMap m_SpeedControl;
        private List<ISpeedControlActions> m_SpeedControlActionsCallbackInterfaces = new List<ISpeedControlActions>();
        private readonly InputAction m_SpeedControl_SpeedControl_0;
        private readonly InputAction m_SpeedControl_SpeedControl_1;
        private readonly InputAction m_SpeedControl_SpeedControl_2;
        private readonly InputAction m_SpeedControl_SpeedControl_3;
        public struct SpeedControlActions
        {
            private @GameplayInputMaps m_Wrapper;
            public SpeedControlActions(@GameplayInputMaps wrapper) { m_Wrapper = wrapper; }
            public InputAction @SpeedControl_0 => m_Wrapper.m_SpeedControl_SpeedControl_0;
            public InputAction @SpeedControl_1 => m_Wrapper.m_SpeedControl_SpeedControl_1;
            public InputAction @SpeedControl_2 => m_Wrapper.m_SpeedControl_SpeedControl_2;
            public InputAction @SpeedControl_3 => m_Wrapper.m_SpeedControl_SpeedControl_3;
            public InputActionMap Get() { return m_Wrapper.m_SpeedControl; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(SpeedControlActions set) { return set.Get(); }
            public void AddCallbacks(ISpeedControlActions instance)
            {
                if (instance == null || m_Wrapper.m_SpeedControlActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_SpeedControlActionsCallbackInterfaces.Add(instance);
                @SpeedControl_0.started += instance.OnSpeedControl_0;
                @SpeedControl_0.performed += instance.OnSpeedControl_0;
                @SpeedControl_0.canceled += instance.OnSpeedControl_0;
                @SpeedControl_1.started += instance.OnSpeedControl_1;
                @SpeedControl_1.performed += instance.OnSpeedControl_1;
                @SpeedControl_1.canceled += instance.OnSpeedControl_1;
                @SpeedControl_2.started += instance.OnSpeedControl_2;
                @SpeedControl_2.performed += instance.OnSpeedControl_2;
                @SpeedControl_2.canceled += instance.OnSpeedControl_2;
                @SpeedControl_3.started += instance.OnSpeedControl_3;
                @SpeedControl_3.performed += instance.OnSpeedControl_3;
                @SpeedControl_3.canceled += instance.OnSpeedControl_3;
            }

            private void UnregisterCallbacks(ISpeedControlActions instance)
            {
                @SpeedControl_0.started -= instance.OnSpeedControl_0;
                @SpeedControl_0.performed -= instance.OnSpeedControl_0;
                @SpeedControl_0.canceled -= instance.OnSpeedControl_0;
                @SpeedControl_1.started -= instance.OnSpeedControl_1;
                @SpeedControl_1.performed -= instance.OnSpeedControl_1;
                @SpeedControl_1.canceled -= instance.OnSpeedControl_1;
                @SpeedControl_2.started -= instance.OnSpeedControl_2;
                @SpeedControl_2.performed -= instance.OnSpeedControl_2;
                @SpeedControl_2.canceled -= instance.OnSpeedControl_2;
                @SpeedControl_3.started -= instance.OnSpeedControl_3;
                @SpeedControl_3.performed -= instance.OnSpeedControl_3;
                @SpeedControl_3.canceled -= instance.OnSpeedControl_3;
            }

            public void RemoveCallbacks(ISpeedControlActions instance)
            {
                if (m_Wrapper.m_SpeedControlActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(ISpeedControlActions instance)
            {
                foreach (var item in m_Wrapper.m_SpeedControlActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_SpeedControlActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public SpeedControlActions @SpeedControl => new SpeedControlActions(this);
        public interface ICommonActions
        {
            void OnMouseLeftClick(InputAction.CallbackContext context);
            void OnMouseRightClick(InputAction.CallbackContext context);
            void OnMousePosition(InputAction.CallbackContext context);
            void OnEscape(InputAction.CallbackContext context);
            void OnAltHotKey(InputAction.CallbackContext context);
            void OnCtrlHotKey(InputAction.CallbackContext context);
        }
        public interface ITopdownActions
        {
            void OnZoom(InputAction.CallbackContext context);
            void OnDragActivation(InputAction.CallbackContext context);
            void OnDragPerform(InputAction.CallbackContext context);
            void OnConfirm(InputAction.CallbackContext context);
            void OnFocus(InputAction.CallbackContext context);
            void OnReposition(InputAction.CallbackContext context);
        }
        public interface IConstructingActions
        {
            void OnSwitchConstructStatus(InputAction.CallbackContext context);
            void OnConstructOrbit(InputAction.CallbackContext context);
            void OnConstructPlanet(InputAction.CallbackContext context);
        }
        public interface IAbilityCastActions
        {
            void OnAbilityCast_Q(InputAction.CallbackContext context);
            void OnAbilityCast_W(InputAction.CallbackContext context);
            void OnAbilityCast_E(InputAction.CallbackContext context);
            void OnAbilityCast_R(InputAction.CallbackContext context);
            void OnAbilityCast_T(InputAction.CallbackContext context);
            void OnAbilityCast_Y(InputAction.CallbackContext context);
            void OnSelectorPosition(InputAction.CallbackContext context);
            void OnSelectorConfirm(InputAction.CallbackContext context);
            void OnSelectorCancel(InputAction.CallbackContext context);
        }
        public interface ISpeedControlActions
        {
            void OnSpeedControl_0(InputAction.CallbackContext context);
            void OnSpeedControl_1(InputAction.CallbackContext context);
            void OnSpeedControl_2(InputAction.CallbackContext context);
            void OnSpeedControl_3(InputAction.CallbackContext context);
        }
    }
}
