
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.ability
{
/// <summary>
/// 技能-策略释放组
/// </summary>
public sealed partial class CastPair : Luban.BeanBase
{
    public CastPair(JSONNode _buf) 
    {
        { if(!_buf["abilityId"].IsNumber) { throw new SerializationException(); }  AbilityId = _buf["abilityId"]; }
        AbilityId_Ref = null;
        { if(!_buf["strategyType"].IsString) { throw new SerializationException(); }  StrategyType = _buf["strategyType"]; }
    }

    public static CastPair DeserializeCastPair(JSONNode _buf)
    {
        return new ability.CastPair(_buf);
    }

    public readonly int AbilityId;
    public Ability AbilityId_Ref;
    public readonly string StrategyType;
   
    public const int __ID__ = -504141027;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        AbilityId_Ref = tables.TbAbility.GetOrDefault(AbilityId);
    }

    public override string ToString()
    {
        return "{ "
        + "abilityId:" + AbilityId + ","
        + "strategyType:" + StrategyType + ","
        + "}";
    }
}

}

