
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class Ability : Luban.BeanBase
{
    public Ability(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["ability_name"].IsString) { throw new SerializationException(); }  AbilityName = _buf["ability_name"]; }
        { if(!_buf["ability_desc"].IsString) { throw new SerializationException(); }  AbilityDesc = _buf["ability_desc"]; }
        { if(!_buf["ability_type_full_name"].IsString) { throw new SerializationException(); }  AbilityTypeFullName = _buf["ability_type_full_name"]; }
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
        { if(!_buf["channel_time"].IsNumber) { throw new SerializationException(); }  ChannelTime = _buf["channel_time"]; }
        { if(!_buf["effect_time"].IsNumber) { throw new SerializationException(); }  EffectTime = _buf["effect_time"]; }
        { if(!_buf["cast_range"].IsNumber) { throw new SerializationException(); }  CastRange = _buf["cast_range"]; }
        { if(!_buf["basic_damage"].IsNumber) { throw new SerializationException(); }  BasicDamage = _buf["basic_damage"]; }
        { if(!_buf["require_target"].IsBoolean) { throw new SerializationException(); }  RequireTarget = _buf["require_target"]; }
        { if(!_buf["icon_asset_id"].IsString) { throw new SerializationException(); }  IconAssetId = _buf["icon_asset_id"]; }
    }

    public static Ability DeserializeAbility(JSONNode _buf)
    {
        return new Ability(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 技能名称
    /// </summary>
    public readonly string AbilityName;
    /// <summary>
    /// 技能描述
    /// </summary>
    public readonly string AbilityDesc;
    /// <summary>
    /// 逻辑类型(FullName)
    /// </summary>
    public readonly string AbilityTypeFullName;
    /// <summary>
    /// 冷却时间
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 引导时间
    /// </summary>
    public readonly float ChannelTime;
    /// <summary>
    /// 持续时间
    /// </summary>
    public readonly float EffectTime;
    /// <summary>
    /// 施放范围
    /// </summary>
    public readonly float CastRange;
    /// <summary>
    /// 基础伤害
    /// </summary>
    public readonly int BasicDamage;
    /// <summary>
    /// 需要目标
    /// </summary>
    public readonly bool RequireTarget;
    /// <summary>
    /// 图标资源
    /// </summary>
    public readonly string IconAssetId;
   
    public const int __ID__ = 464145674;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "abilityName:" + AbilityName + ","
        + "abilityDesc:" + AbilityDesc + ","
        + "abilityTypeFullName:" + AbilityTypeFullName + ","
        + "cooldown:" + Cooldown + ","
        + "channelTime:" + ChannelTime + ","
        + "effectTime:" + EffectTime + ","
        + "castRange:" + CastRange + ","
        + "basicDamage:" + BasicDamage + ","
        + "requireTarget:" + RequireTarget + ","
        + "iconAssetId:" + IconAssetId + ","
        + "}";
    }
}

}

