
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class Building : Luban.BeanBase
{
    public Building(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["slot_req"].IsNumber) { throw new SerializationException(); }  SlotReq = _buf["slot_req"]; }
        { if(!_buf["attach_type"].IsNumber) { throw new SerializationException(); }  AttachType = (building.EDeployType)_buf["attach_type"].AsInt; }
        { if(!_buf["building_type"].IsNumber) { throw new SerializationException(); }  BuildingType = (building.EBuildingType)_buf["building_type"].AsInt; }
        { var __json0 = _buf["suitable_recipe"]; if(!__json0.IsArray) { throw new SerializationException(); } SuitableRecipe = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SuitableRecipe.Add(__v0); }   }
        { if(!_buf["ability_cast_pair"].IsObject) { throw new SerializationException(); }  AbilityCastPair = ability.CastPair.DeserializeCastPair(_buf["ability_cast_pair"]);  }
        { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["prefab"]; }
    }

    public static Building DeserializeBuilding(JSONNode _buf)
    {
        return new Building(_buf);
    }

    /// <summary>
    /// 建筑ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述文本
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 槽位消耗数量
    /// </summary>
    public readonly int SlotReq;
    /// <summary>
    /// 依附轨道类型
    /// </summary>
    public readonly building.EDeployType AttachType;
    /// <summary>
    /// 建筑类型
    /// </summary>
    public readonly building.EBuildingType BuildingType;
    /// <summary>
    /// 适配生产链
    /// </summary>
    public readonly System.Collections.Generic.List<int> SuitableRecipe;
    public System.Collections.Generic.List<Recipe> SuitableRecipe_Ref;
    public readonly ability.CastPair AbilityCastPair;
    /// <summary>
    /// 图标资源
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 实体预制资源
    /// </summary>
    public readonly string Prefab;
   
    public const int __ID__ = -1366001964;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        SuitableRecipe_Ref = new System.Collections.Generic.List<Recipe>();
        foreach (var _v in SuitableRecipe) { SuitableRecipe_Ref.Add(tables.TbRecipe.GetOrDefault(_v)); }

        AbilityCastPair?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "slotReq:" + SlotReq + ","
        + "attachType:" + AttachType + ","
        + "buildingType:" + BuildingType + ","
        + "suitableRecipe:" + Luban.StringUtil.CollectionToString(SuitableRecipe) + ","
        + "abilityCastPair:" + AbilityCastPair + ","
        + "icon:" + Icon + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}

}

