
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.building
{ 
    /// <summary>
    /// 建筑部署类型
    /// </summary>
    public enum EDeployType
    {
        /// <summary>
        /// 地表
        /// </summary>
        Surface = 1,
        /// <summary>
        /// 近地轨道
        /// </summary>
        LowOrbit = 2,
        /// <summary>
        /// 自由轨道
        /// </summary>
        FreeOrbit = 3,
        /// <summary>
        /// 天体轨道
        /// </summary>
        PlanetOrbit = 4,
    }

} 

