
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.building
{ 
    /// <summary>
    /// 建筑类型
    /// </summary>
    public enum EBuildingType
    {
        /// <summary>
        /// 攻击
        /// </summary>
        Attack = 1,
        /// <summary>
        /// 防御
        /// </summary>
        Defense = 2,
        /// <summary>
        /// 生产
        /// </summary>
        Produce = 3,
        /// <summary>
        /// 合成
        /// </summary>
        Manufacture = 4,
        /// <summary>
        /// 辅助
        /// </summary>
        Assistant = 5,
        /// <summary>
        /// 干扰
        /// </summary>
        Interference = 6,
    }

} 

