
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.building
{
public partial class TbBuilding
{
    private readonly System.Collections.Generic.Dictionary<int, Building> _dataMap;
    private readonly System.Collections.Generic.List<Building> _dataList;
    
    public TbBuilding(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Building>();
        _dataList = new System.Collections.Generic.List<Building>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Building _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Building.DeserializeBuilding(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Building> DataMap => _dataMap;
    public System.Collections.Generic.List<Building> DataList => _dataList;

    public Building GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Building Get(int key) => _dataMap[key];
    public Building this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

