
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.card
{ 
    public enum ETargetType
    {
        /// <summary>
        /// 星系
        /// </summary>
        Galaxy = 1,
        /// <summary>
        /// 星球
        /// </summary>
        Planet = 2,
        /// <summary>
        /// 轨道
        /// </summary>
        Orbit = 3,
        /// <summary>
        /// 无需目标
        /// </summary>
        None = 4,
    }

} 

