
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.card
{
/// <summary>
/// 卡牌资源消耗
/// </summary>
public sealed partial class CostPair : Luban.BeanBase
{
    public CostPair(JSONNode _buf) 
    {
        { if(!_buf["statName"].IsString) { throw new SerializationException(); }  StatName = _buf["statName"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static CostPair DeserializeCostPair(JSONNode _buf)
    {
        return new card.CostPair(_buf);
    }

    public readonly string StatName;
    public readonly int Count;
   
    public const int __ID__ = 1884759429;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "statName:" + StatName + ","
        + "count:" + Count + ","
        + "}";
    }
}

}

