
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class Card : Luban.BeanBase
{
    public Card(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["faction_belong"].IsString) { throw new SerializationException(); }  FactionBelong = _buf["faction_belong"]; }
        { if(!_buf["target_type"].IsNumber) { throw new SerializationException(); }  TargetType = (card.ETargetType)_buf["target_type"].AsInt; }
        { if(!_buf["card_type"].IsNumber) { throw new SerializationException(); }  CardType = (card.ECardType)_buf["card_type"].AsInt; }
        { var __json0 = _buf["mod_id_list"]; if(!__json0.IsArray) { throw new SerializationException(); } ModIdList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ModIdList.Add(__v0); }   }
        { if(!_buf["icon_asset_id"].IsString) { throw new SerializationException(); }  IconAssetId = _buf["icon_asset_id"]; }
    }

    public static Card DeserializeCard(JSONNode _buf)
    {
        return new Card(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 所属派系
    /// </summary>
    public readonly string FactionBelong;
    public readonly card.ETargetType TargetType;
    /// <summary>
    /// 卡片类型
    /// </summary>
    public readonly card.ECardType CardType;
    /// <summary>
    /// 修改器列表
    /// </summary>
    public readonly System.Collections.Generic.List<int> ModIdList;
    /// <summary>
    /// 图标资源ID
    /// </summary>
    public readonly string IconAssetId;
   
    public const int __ID__ = 2092848;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "factionBelong:" + FactionBelong + ","
        + "targetType:" + TargetType + ","
        + "cardType:" + CardType + ","
        + "modIdList:" + Luban.StringUtil.CollectionToString(ModIdList) + ","
        + "iconAssetId:" + IconAssetId + ","
        + "}";
    }
}

}

