
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.card
{ 
    public enum ECardType
    {
        /// <summary>
        /// 设施、装置（使用修改器）
        /// </summary>
        Facility = 1,
        /// <summary>
        /// 生产、合成、研发
        /// </summary>
        Engineering = 2,
        /// <summary>
        /// 附魔、修改器
        /// </summary>
        Strategy = 3,
        /// <summary>
        /// 触发事件、获得资源、改变游戏进程
        /// </summary>
        Chance = 4,
        /// <summary>
        /// 持有会造成负面影响，需要消除
        /// </summary>
        Challenge = 5,
    }

} 

