
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.card
{
public partial class TbCard
{
    private readonly System.Collections.Generic.Dictionary<int, Card> _dataMap;
    private readonly System.Collections.Generic.List<Card> _dataList;
    
    public TbCard(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Card>();
        _dataList = new System.Collections.Generic.List<Card>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Card _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Card.DeserializeCard(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Card> DataMap => _dataMap;
    public System.Collections.Generic.List<Card> DataList => _dataList;

    public Card GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Card Get(int key) => _dataMap[key];
    public Card this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

