
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.cosmos
{
public partial class TbPlanet
{
    private readonly System.Collections.Generic.Dictionary<int, Planet> _dataMap;
    private readonly System.Collections.Generic.List<Planet> _dataList;
    
    public TbPlanet(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Planet>();
        _dataList = new System.Collections.Generic.List<Planet>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Planet _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Planet.DeserializePlanet(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Planet> DataMap => _dataMap;
    public System.Collections.Generic.List<Planet> DataList => _dataList;

    public Planet GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Planet Get(int key) => _dataMap[key];
    public Planet this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

