
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.cosmos
{
public partial class TbGalaxy
{
    private readonly System.Collections.Generic.Dictionary<int, Galaxy> _dataMap;
    private readonly System.Collections.Generic.List<Galaxy> _dataList;
    
    public TbGalaxy(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Galaxy>();
        _dataList = new System.Collections.Generic.List<Galaxy>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Galaxy _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Galaxy.DeserializeGalaxy(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Galaxy> DataMap => _dataMap;
    public System.Collections.Generic.List<Galaxy> DataList => _dataList;

    public Galaxy GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Galaxy Get(int key) => _dataMap[key];
    public Galaxy this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

