
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class Galaxy : Luban.BeanBase
{
    public Galaxy(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["factionId"].IsNumber) { throw new SerializationException(); }  FactionId = _buf["factionId"]; }
        { if(!_buf["icon_asset_id"].IsString) { throw new SerializationException(); }  IconAssetId = _buf["icon_asset_id"]; }
        { if(!_buf["setting"].IsString) { throw new SerializationException(); }  Setting = _buf["setting"]; }
    }

    public static Galaxy DeserializeGalaxy(JSONNode _buf)
    {
        return new Galaxy(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 适用派系
    /// </summary>
    public readonly int FactionId;
    /// <summary>
    /// 图标资源
    /// </summary>
    public readonly string IconAssetId;
    /// <summary>
    /// 星系解析资源
    /// </summary>
    public readonly string Setting;
   
    public const int __ID__ = 2125565744;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "factionId:" + FactionId + ","
        + "iconAssetId:" + IconAssetId + ","
        + "setting:" + Setting + ","
        + "}";
    }
}

}

