
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.incident
{
public partial class TbIncident
{
    private readonly System.Collections.Generic.Dictionary<int, Incident> _dataMap;
    private readonly System.Collections.Generic.List<Incident> _dataList;
    
    public TbIncident(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Incident>();
        _dataList = new System.Collections.Generic.List<Incident>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Incident _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Incident.DeserializeIncident(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Incident> DataMap => _dataMap;
    public System.Collections.Generic.List<Incident> DataList => _dataList;

    public Incident GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Incident Get(int key) => _dataMap[key];
    public Incident this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

