
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class Incident : Luban.BeanBase
{
    public Incident(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["title"].IsString) { throw new SerializationException(); }  Title = _buf["title"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["incident_type"].IsNumber) { throw new SerializationException(); }  IncidentType = (incident.EIncidentType)_buf["incident_type"].AsInt; }
        { if(!_buf["has_duraction"].IsBoolean) { throw new SerializationException(); }  HasDuraction = _buf["has_duraction"]; }
        { if(!_buf["duration"].IsNumber) { throw new SerializationException(); }  Duration = _buf["duration"]; }
        { if(!_buf["cooldown"].IsNumber) { throw new SerializationException(); }  Cooldown = _buf["cooldown"]; }
        { if(!_buf["pending"].IsBoolean) { throw new SerializationException(); }  Pending = _buf["pending"]; }
        { var __json0 = _buf["option_list"]; if(!__json0.IsArray) { throw new SerializationException(); } OptionList = new System.Collections.Generic.List<incident.ResponseOption>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { incident.ResponseOption __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = incident.ResponseOption.DeserializeResponseOption(__e0);  }  OptionList.Add(__v0); }   }
    }

    public static Incident DeserializeIncident(JSONNode _buf)
    {
        return new Incident(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 标题
    /// </summary>
    public readonly string Title;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 是否可堆叠
    /// </summary>
    public readonly incident.EIncidentType IncidentType;
    /// <summary>
    /// 是否有时限
    /// </summary>
    public readonly bool HasDuraction;
    /// <summary>
    /// 时间限制
    /// </summary>
    public readonly float Duration;
    /// <summary>
    /// 冷却
    /// </summary>
    public readonly float Cooldown;
    /// <summary>
    /// 是否必须处理
    /// </summary>
    public readonly bool Pending;
    public readonly System.Collections.Generic.List<incident.ResponseOption> OptionList;
   
    public const int __ID__ = 151628018;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in OptionList) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "title:" + Title + ","
        + "description:" + Description + ","
        + "incidentType:" + IncidentType + ","
        + "hasDuraction:" + HasDuraction + ","
        + "duration:" + Duration + ","
        + "cooldown:" + Cooldown + ","
        + "pending:" + Pending + ","
        + "optionList:" + Luban.StringUtil.CollectionToString(OptionList) + ","
        + "}";
    }
}

}

