
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.incident
{
/// <summary>
/// 回复选项
/// </summary>
public sealed partial class ResponseOption : Luban.BeanBase
{
    public ResponseOption(JSONNode _buf) 
    {
        { if(!_buf["conditionTag"].IsString) { throw new SerializationException(); }  ConditionTag = _buf["conditionTag"]; }
        { if(!_buf["callbackTag"].IsString) { throw new SerializationException(); }  CallbackTag = _buf["callbackTag"]; }
        { if(!_buf["responseText"].IsString) { throw new SerializationException(); }  ResponseText = _buf["responseText"]; }
    }

    public static ResponseOption DeserializeResponseOption(JSONNode _buf)
    {
        return new incident.ResponseOption(_buf);
    }

    public readonly string ConditionTag;
    public readonly string CallbackTag;
    public readonly string ResponseText;
   
    public const int __ID__ = -940002094;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "conditionTag:" + ConditionTag + ","
        + "callbackTag:" + CallbackTag + ","
        + "responseText:" + ResponseText + ","
        + "}";
    }
}

}

