
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.incident
{ 
    /// <summary>
    /// 遭遇事件
    /// </summary>
    public enum EIncidentType
    {
        /// <summary>
        /// 遭遇
        /// </summary>
        Enconter = 1,
        /// <summary>
        /// 交易
        /// </summary>
        Trade = 2,
        /// <summary>
        /// 突袭
        /// </summary>
        Raid = 3,
        /// <summary>
        /// 探索
        /// </summary>
        Exploration = 4,
        /// <summary>
        /// 长线调查，或许能开启下一个事件
        /// </summary>
        Investigation = 5,
        /// <summary>
        /// 任务
        /// </summary>
        Quest = 6,
        /// <summary>
        /// 世界变化
        /// </summary>
        World = 7,
    }

} 

