
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    /// <summary>
    /// 存储需求主条件
    /// </summary>
    public enum EItemStorageCondition
    {
        /// <summary>
        /// 无特殊需求
        /// </summary>
        None = 0,
        /// <summary>
        /// 低温存储
        /// </summary>
        LowTemperature = 1,
        /// <summary>
        /// 高压存储
        /// </summary>
        HighPressure = 2,
        /// <summary>
        /// 电磁屏蔽
        /// </summary>
        ElectricShielding = 3,
        /// <summary>
        /// 磁约束容器
        /// </summary>
        MagneticConfinement = 4,
    }

} 

