
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    /// <summary>
    /// 物态/相态
    /// </summary>
    public enum EItemPhysicalState
    {
        /// <summary>
        /// 固态
        /// </summary>
        Solid = 1,
        /// <summary>
        /// 液态
        /// </summary>
        Liquid = 2,
        /// <summary>
        /// 气态
        /// </summary>
        Gas = 3,
        /// <summary>
        /// 等离子态
        /// </summary>
        Plasma = 4,
        /// <summary>
        /// 量子相态
        /// </summary>
        Quantum = 5,
        /// <summary>
        /// 奇异态/非常规
        /// </summary>
        Exotic = 6,
    }

} 

