
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.item
{
/// <summary>
/// 物品三维属性：结构/化学/场域
/// </summary>
public sealed partial class ItemStats : Luban.BeanBase
{
    public ItemStats(JSONNode _buf) 
    {
        { if(!_buf["structure"].IsNumber) { throw new SerializationException(); }  Structure = _buf["structure"]; }
        { if(!_buf["chemical"].IsNumber) { throw new SerializationException(); }  Chemical = _buf["chemical"]; }
        { if(!_buf["field"].IsNumber) { throw new SerializationException(); }  Field = _buf["field"]; }
    }

    public static ItemStats DeserializeItemStats(JSONNode _buf)
    {
        return new item.ItemStats(_buf);
    }

    /// <summary>
    /// 结构强度(0-5)
    /// </summary>
    public readonly int Structure;
    /// <summary>
    /// 化学反应性(0-5)
    /// </summary>
    public readonly int Chemical;
    /// <summary>
    /// 场域敏感度(0-5)
    /// </summary>
    public readonly int Field;
   
    public const int __ID__ = 36225041;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "structure:" + Structure + ","
        + "chemical:" + Chemical + ","
        + "field:" + Field + ","
        + "}";
    }
}

}

