
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["description"].IsString) { throw new SerializationException(); }  Description = _buf["description"]; }
        { if(!_buf["item_type"].IsNumber) { throw new SerializationException(); }  ItemType = (item.EItemType)_buf["item_type"].AsInt; }
        { if(!_buf["can_sell"].IsBoolean) { throw new SerializationException(); }  CanSell = _buf["can_sell"]; }
        { if(!_buf["price"].IsNumber) { throw new SerializationException(); }  Price = _buf["price"]; }
        { if(!_buf["can_stack"].IsBoolean) { throw new SerializationException(); }  CanStack = _buf["can_stack"]; }
        { if(!_buf["max_stack"].IsNumber) { throw new SerializationException(); }  MaxStack = _buf["max_stack"]; }
        { if(!_buf["can_use"].IsBoolean) { throw new SerializationException(); }  CanUse = _buf["can_use"]; }
        { if(!_buf["use_target_type"].IsNumber) { throw new SerializationException(); }  UseTargetType = (item.EUseTargetType)_buf["use_target_type"].AsInt; }
        { if(!_buf["tier"].IsNumber) { throw new SerializationException(); }  Tier = _buf["tier"]; }
        { if(!_buf["physical_state"].IsNumber) { throw new SerializationException(); }  PhysicalState = (item.EItemPhysicalState)_buf["physical_state"].AsInt; }
        { if(!_buf["stat_struct"].IsObject) { throw new SerializationException(); }  StatStruct = item.ItemStats.DeserializeItemStats(_buf["stat_struct"]);  }
        { if(!_buf["storage_condition"].IsNumber) { throw new SerializationException(); }  StorageCondition = (item.EItemStorageCondition)_buf["storage_condition"].AsInt; }
        { if(!_buf["payload_type"].IsNumber) { throw new SerializationException(); }  PayloadType = (payload.EPayloadType)_buf["payload_type"].AsInt; }
        { if(!_buf["icon_asset_id"].IsString) { throw new SerializationException(); }  IconAssetId = _buf["icon_asset_id"]; }
        { if(!_buf["prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["prefab"]; }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new Item(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 物品类型
    /// </summary>
    public readonly item.EItemType ItemType;
    /// <summary>
    /// 是否可售卖
    /// </summary>
    public readonly bool CanSell;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 是否可堆叠
    /// </summary>
    public readonly bool CanStack;
    /// <summary>
    /// 最大堆叠数
    /// </summary>
    public readonly int MaxStack;
    /// <summary>
    /// 是否可使用
    /// </summary>
    public readonly bool CanUse;
    /// <summary>
    /// 使用目标类型
    /// </summary>
    public readonly item.EUseTargetType UseTargetType;
    /// <summary>
    /// 层级
    /// </summary>
    public readonly int Tier;
    /// <summary>
    /// 物态
    /// </summary>
    public readonly item.EItemPhysicalState PhysicalState;
    public readonly item.ItemStats StatStruct;
    /// <summary>
    /// 存储条件
    /// </summary>
    public readonly item.EItemStorageCondition StorageCondition;
    /// <summary>
    /// 载荷来源
    /// </summary>
    public readonly payload.EPayloadType PayloadType;
    /// <summary>
    /// 图标资源
    /// </summary>
    public readonly string IconAssetId;
    /// <summary>
    /// 实体预制路径
    /// </summary>
    public readonly string Prefab;
   
    public const int __ID__ = 2289459;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        StatStruct?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "itemType:" + ItemType + ","
        + "canSell:" + CanSell + ","
        + "price:" + Price + ","
        + "canStack:" + CanStack + ","
        + "maxStack:" + MaxStack + ","
        + "canUse:" + CanUse + ","
        + "useTargetType:" + UseTargetType + ","
        + "tier:" + Tier + ","
        + "physicalState:" + PhysicalState + ","
        + "statStruct:" + StatStruct + ","
        + "storageCondition:" + StorageCondition + ","
        + "payloadType:" + PayloadType + ","
        + "iconAssetId:" + IconAssetId + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}

}

