
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.item
{ 
    /// <summary>
    /// 物品类型
    /// </summary>
    public enum EItemType
    {
        /// <summary>
        /// 原始资源
        /// </summary>
        RawRes = 1,
        /// <summary>
        /// 复合资源
        /// </summary>
        CompRes = 2,
        /// <summary>
        /// 建筑部署器
        /// </summary>
        Deployer = 3,
        /// <summary>
        /// 装置
        /// </summary>
        Device = 4,
        /// <summary>
        /// 遗物
        /// </summary>
        Relic = 5,
    }

} 

