
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace GameConfig.payload
{ 
    /// <summary>
    /// 载荷类型
    /// </summary>
    public enum EPayloadType
    {
        /// <summary>
        /// 基本就是游戏有多少中实体类，就有多少种载荷类型
        /// </summary>
        None = 0,
        /// <summary>
        /// 建筑
        /// </summary>
        Building = 1,
        /// <summary>
        /// 物资
        /// </summary>
        Item = 2,
        /// <summary>
        /// 星球
        /// </summary>
        Planet = 3,
    }

} 

