
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.planet
{
/// <summary>
/// 星球基本属性
/// </summary>
public sealed partial class PlanetStats : Luban.BeanBase
{
    public PlanetStats(JSONNode _buf) 
    {
        { if(!_buf["thermalEnergy"].IsNumber) { throw new SerializationException(); }  ThermalEnergy = _buf["thermalEnergy"]; }
        { if(!_buf["electromagneticStrength"].IsNumber) { throw new SerializationException(); }  ElectromagneticStrength = _buf["electromagneticStrength"]; }
        { if(!_buf["structuralIntegrity"].IsNumber) { throw new SerializationException(); }  StructuralIntegrity = _buf["structuralIntegrity"]; }
        { if(!_buf["gravityStrength"].IsNumber) { throw new SerializationException(); }  GravityStrength = _buf["gravityStrength"]; }
        { if(!_buf["chemicalActivity"].IsNumber) { throw new SerializationException(); }  ChemicalActivity = _buf["chemicalActivity"]; }
        { if(!_buf["anchorSensitivity"].IsNumber) { throw new SerializationException(); }  AnchorSensitivity = _buf["anchorSensitivity"]; }
    }

    public static PlanetStats DeserializePlanetStats(JSONNode _buf)
    {
        return new planet.PlanetStats(_buf);
    }

    public readonly int ThermalEnergy;
    public readonly int ElectromagneticStrength;
    public readonly int StructuralIntegrity;
    public readonly int GravityStrength;
    public readonly int ChemicalActivity;
    public readonly int AnchorSensitivity;
   
    public const int __ID__ = -1098461583;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "thermalEnergy:" + ThermalEnergy + ","
        + "electromagneticStrength:" + ElectromagneticStrength + ","
        + "structuralIntegrity:" + StructuralIntegrity + ","
        + "gravityStrength:" + GravityStrength + ","
        + "chemicalActivity:" + ChemicalActivity + ","
        + "anchorSensitivity:" + AnchorSensitivity + ","
        + "}";
    }
}

}

