
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class Planet : Luban.BeanBase
{
    public Planet(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["stats"].IsObject) { throw new SerializationException(); }  Stats = planet.PlanetStats.DeserializePlanetStats(_buf["stats"]);  }
        { if(!_buf["icon_asset_id"].IsString) { throw new SerializationException(); }  IconAssetId = _buf["icon_asset_id"]; }
        { if(!_buf["prefab"].IsString) { throw new SerializationException(); }  Prefab = _buf["prefab"]; }
    }

    public static Planet DeserializePlanet(JSONNode _buf)
    {
        return new Planet(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    public readonly planet.PlanetStats Stats;
    /// <summary>
    /// 图标资源
    /// </summary>
    public readonly string IconAssetId;
    /// <summary>
    /// 实体预制路径
    /// </summary>
    public readonly string Prefab;
   
    public const int __ID__ = -1901896264;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Stats?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "stats:" + Stats + ","
        + "iconAssetId:" + IconAssetId + ","
        + "prefab:" + Prefab + ","
        + "}";
    }
}

}

