
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.recipe
{
public partial class TbRecipe
{
    private readonly System.Collections.Generic.Dictionary<int, Recipe> _dataMap;
    private readonly System.Collections.Generic.List<Recipe> _dataList;
    
    public TbRecipe(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Recipe>();
        _dataList = new System.Collections.Generic.List<Recipe>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Recipe _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = Recipe.DeserializeRecipe(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Recipe> DataMap => _dataMap;
    public System.Collections.Generic.List<Recipe> DataList => _dataList;

    public Recipe GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Recipe Get(int key) => _dataMap[key];
    public Recipe this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

