
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig
{
public sealed partial class Recipe : Luban.BeanBase
{
    public Recipe(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["workload"].IsNumber) { throw new SerializationException(); }  Workload = _buf["workload"]; }
        { if(!_buf["tier"].IsNumber) { throw new SerializationException(); }  Tier = _buf["tier"]; }
        { var __json0 = _buf["input_items"]; if(!__json0.IsArray) { throw new SerializationException(); } InputItems = new System.Collections.Generic.List<recipe.RecipeItem>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { recipe.RecipeItem __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = recipe.RecipeItem.DeserializeRecipeItem(__e0);  }  InputItems.Add(__v0); }   }
        { var __json0 = _buf["output_items"]; if(!__json0.IsArray) { throw new SerializationException(); } OutputItems = new System.Collections.Generic.List<recipe.RecipeItem>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { recipe.RecipeItem __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = recipe.RecipeItem.DeserializeRecipeItem(__e0);  }  OutputItems.Add(__v0); }   }
    }

    public static Recipe DeserializeRecipe(JSONNode _buf)
    {
        return new Recipe(_buf);
    }

    /// <summary>
    /// 配方ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 配方名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述文本
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 工作量
    /// </summary>
    public readonly int Workload;
    /// <summary>
    /// 配方阶级
    /// </summary>
    public readonly int Tier;
    /// <summary>
    /// 输入物品列表
    /// </summary>
    public readonly System.Collections.Generic.List<recipe.RecipeItem> InputItems;
    /// <summary>
    /// 输出物品列表
    /// </summary>
    public readonly System.Collections.Generic.List<recipe.RecipeItem> OutputItems;
   
    public const int __ID__ = -1851047506;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in InputItems) { _e?.ResolveRef(tables); }
        foreach (var _e in OutputItems) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "workload:" + Workload + ","
        + "tier:" + Tier + ","
        + "inputItems:" + Luban.StringUtil.CollectionToString(InputItems) + ","
        + "outputItems:" + Luban.StringUtil.CollectionToString(OutputItems) + ","
        + "}";
    }
}

}

