
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace GameConfig.recipe
{
/// <summary>
/// 合成输入及输出
/// </summary>
public sealed partial class RecipeItem : Luban.BeanBase
{
    public RecipeItem(JSONNode _buf) 
    {
        { if(!_buf["itemId"].IsNumber) { throw new SerializationException(); }  ItemId = _buf["itemId"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
    }

    public static RecipeItem DeserializeRecipeItem(JSONNode _buf)
    {
        return new recipe.RecipeItem(_buf);
    }

    public readonly int ItemId;
    public readonly int Count;
   
    public const int __ID__ = -748810687;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemId:" + ItemId + ","
        + "count:" + Count + ","
        + "}";
    }
}

}

